# Generated by Django 3.2 on 2021-04-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=30, verbose_name='pseudonim'),
        ),
    ]
